name: dnora2
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.13
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.7
  - pandas
  - xarray>=0.20.1
  - netcdf4
  - meshio
  - geo-skeletons>=0.20.14
  - pytest
  - pip
  - pip:
    - dnplot>=0.4.2
  - python-dotenv
  - cdsapi>=0.7.6
  - progressbar
