name: dnora2
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.7
  - pandas
  - xarray>=0.20.1
  - netcdf4
  - meshio
  - geo-skeletons=0.21.1
  - geo-parameters>=0.11.0
  - pytest
  - pip
  - pip:
    - dnplot>=0.4.3
  - python-dotenv
  - cdsapi>=0.7.6
  - progressbar
  - scikit-learn
