name: dnora2
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.11
  - numpy>=1.17
  - scipy>=1.7
  - pandas
  - xarray>=0.20.1
  - netcdf4
  - meshio
  - geo-skeletons=0.20.*
  - pytest
  - pip
  - pip:
    - dnplot
  - python-dotenv
  - cdsapi>=0.7.6
  - progressbar
